const GET_COMMENTS = 'comments/GET_COMMENTS';
const GET_COMMENTS_FAIL = 'comments/GET_COMMENTS_FAIL';
const SAVE_COMMENTS = 'comments/SAVE_COMMENTS';
const DELETE_COMMENTS = 'comments/DELETE_COMMENTS';

export default {
  GET_COMMENTS,
  GET_COMMENTS_FAIL,
  SAVE_COMMENTS,
  DELETE_COMMENTS,
};
